spring:
  datasource:
    url: jdbc:postgresql://localhost:2345/retail
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        hikari:
          minimumIdle: 5
          maximumPoolSize: 20
          idleTimeout: 30000
          connectionTimeout: 30000