services:
  postgres:
    image: postgres:latest
    container_name: postgres-15
    environment:
      POSTGRES_DB: retail
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "2345:5432"
    networks:
      - db-network

networks:
  db-network:
    driver: bridge

volumes:
  pgadmin_data: